export const ACCOUNT_LOGIN = 'ACCOUNT_LOGIN';
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

export const GET_POPULAR_BOOKS = 'GET_POPULAR_BOOKS';
