export const ACCOUNT_CREATE_START = 'ACCOUNT_CREATE_START';
export const ACCOUNT_CREATE_SUCCESS = 'ACCOUNT_CREATE_SUCCESS';
export const ACCOUNT_CREATE_FAILURE = 'ACCOUNT_CREATE_FAILURE';

export const ACCOUNT_LOGIN_START = 'ACCOUNT_LOGIN_START';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGIN_FAILURE = 'ACCOUNT_LOGIN_FAILURE';

export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT';

export const FETCH_BOOKS_START = 'FETCH_BOOKS_START';
export const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export const FETCH_BOOKS_FAILURE = 'FETCH_BOOKS_FAILURE';

export const FETCH_CATEGORIES_SATART = 'FETCH_CATEGORIES_SATART';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';

export const GET_BOOK = 'GET_BOOK';

export const SET_LOCALE = 'SET_LOCALE';

export const SEARCH_BOOKS = 'SEARCH_BOOKS';
